"""empty message

Revision ID: 2f1f090d13ef
Revises: 6ffa2aaec050
Create Date: 2023-07-31 15:52:17.558118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f1f090d13ef'
down_revision = '6ffa2aaec050'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
