"""empty message

Revision ID: 48493bc86185
Revises: ce69d92a3235
Create Date: 2023-07-31 16:05:58.797481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48493bc86185'
down_revision = 'ce69d92a3235'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
