"""empty message

Revision ID: bdce2b5c6998
Revises: b44657b34d64
Create Date: 2023-07-31 15:28:41.271125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdce2b5c6998'
down_revision = 'b44657b34d64'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
