"""empty message

Revision ID: c68bcf1ae0e2
Revises: 7f5c4c2f3455
Create Date: 2023-07-31 15:38:57.240300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c68bcf1ae0e2'
down_revision = '7f5c4c2f3455'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
