"""empty message

Revision ID: ce69d92a3235
Revises: 2f1f090d13ef
Create Date: 2023-07-31 16:01:11.591320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce69d92a3235'
down_revision = '2f1f090d13ef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
